name: Hello Node.js Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Say Hello
        run: echo "Hello from @varshithnomula"
